version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    command: yarn dev
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://pguser:pgpass@db:5432/media_diet_development
    networks:
      - default
    ports:
      - '8787:80'
      - '8788:8788'
    volumes:
      - .:/usr/src/media-diet
      - /usr/src/media-diet/dist
  db:
    image: postgres:10.1
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: media_diet_development
    networks:
      - default
    ports:
      - '9876:5432'
networks:
  default:
