version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: dev.dockerfile
    command: npm run dev
    ports:
      - '8787:80'
      - '8788:8788'
    volumes:
      - .:/usr/src/media-diet
      - /usr/src/media-diet/dist
